/**
 * Admin Contact Message Export API
 * 
 * GET /api/admin/contact-messages/[id]/export
 * 
 * Exports a contact message conversation as PDF
 * Admin-only, protected by requireRole("ADMIN")
 */

export const dynamic = "force-dynamic";

import { NextRequest, NextResponse } from "next/server";
import { requireRole } from "@/lib/auth/requireRole";
import { prisma } from "@/lib/prisma";

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    await requireRole(request, "ADMIN");

    // Fetch message with all related data
    const message = await prisma.contactMessage.findUnique({
      where: { id: params.id },
      include: {
        replies: {
          orderBy: { createdAt: "asc" },
        },
        internalNotes: {
          orderBy: { createdAt: "asc" },
        },
      },
    });

    if (!message) {
      return NextResponse.json(
        { success: false, error: "Contact message not found" },
        { status: 404 }
      );
    }

    // Generate HTML for PDF
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>VelocityMaid — Contact Record</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #1f2937;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
    }
    h1 {
      font-size: 18pt;
      font-weight: 600;
      margin-bottom: 8pt;
      border-bottom: 2px solid #1f2937;
      padding-bottom: 8pt;
    }
    h2 {
      font-size: 14pt;
      font-weight: 600;
      margin-top: 24pt;
      margin-bottom: 8pt;
      color: #374151;
    }
    .meta {
      margin: 16pt 0;
      padding: 12pt;
      background: #f9fafb;
      border-left: 3px solid #1f2937;
    }
    .meta p {
      margin: 4pt 0;
      font-size: 11pt;
    }
    .message {
      margin: 16pt 0;
      padding: 12pt;
      background: #ffffff;
      border: 1px solid #e5e7eb;
      border-radius: 4px;
      white-space: pre-wrap;
    }
    .reply {
      margin: 12pt 0;
      padding: 12pt;
      background: #f9fafb;
      border-left: 3px solid #3b82f6;
      white-space: pre-wrap;
    }
    .reply-meta {
      font-size: 9pt;
      color: #6b7280;
      margin-bottom: 4pt;
    }
    .note {
      margin: 12pt 0;
      padding: 12pt;
      background: #fef3c7;
      border-left: 3px solid #f59e0b;
      font-style: italic;
      white-space: pre-wrap;
    }
    .note-meta {
      font-size: 9pt;
      color: #92400e;
      margin-bottom: 4pt;
    }
    .footer {
      margin-top: 40pt;
      padding-top: 16pt;
      border-top: 1px solid #e5e7eb;
      font-size: 9pt;
      color: #6b7280;
      text-align: center;
    }
  </style>
</head>
<body>
  <h1>VelocityMaid — Contact Record</h1>
  
  <div class="meta">
    <p><strong>Name:</strong> ${escapeHtml(message.name)}</p>
    <p><strong>Email:</strong> ${escapeHtml(message.email)}</p>
    <p><strong>Role:</strong> ${escapeHtml(message.role)}</p>
    ${message.organization ? `<p><strong>Organization:</strong> ${escapeHtml(message.organization)}</p>` : ""}
    <p><strong>Status:</strong> ${escapeHtml(message.status)}</p>
    <p><strong>Received:</strong> ${new Date(message.createdAt).toLocaleString()}</p>
  </div>

  <h2>Original Message</h2>
  <div class="message">${escapeHtml(message.message || "—")}</div>

  ${message.replies.length > 0 ? `
  <h2>Replies (${message.replies.length})</h2>
  ${message.replies.map((reply) => `
    <div class="reply">
      <div class="reply-meta">Reply sent: ${new Date(reply.createdAt).toLocaleString()}</div>
      ${escapeHtml(reply.body)}
    </div>
  `).join("")}
  ` : ""}

  ${message.internalNotes.length > 0 ? `
  <h2>Internal Notes (${message.internalNotes.length})</h2>
  ${message.internalNotes.map((note) => `
    <div class="note">
      <div class="note-meta">Note added: ${new Date(note.createdAt).toLocaleString()}</div>
      ${escapeHtml(note.body)}
    </div>
  `).join("")}
  ` : ""}

  <div class="footer">
    <p>Generated by VelocityMaid on ${new Date().toLocaleString()}</p>
    <p>Infrastructure for trust at scale.</p>
  </div>
</body>
</html>
    `.trim();

    // Return HTML (can be converted to PDF client-side or server-side)
    // For now, return HTML that can be printed to PDF
    return new NextResponse(html, {
      headers: {
        "Content-Type": "text/html",
        "Content-Disposition": `attachment; filename="contact-record-${message.id}.html"`,
      },
    });
  } catch (error: any) {
    console.error("[CONTACT_EXPORT] Error:", error);

    if (error instanceof Response) {
      return error;
    }

    return NextResponse.json(
      {
        success: false,
        error: error?.message || "Failed to export contact record",
        details:
          process.env.NODE_ENV === "development" ? error.stack : undefined,
      },
      { status: 500 }
    );
  }
}

function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}

